### ISSUE TITLE
Project compilation

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Fastino#100]
- 1 Error (needs to be sorted out by changing project settings)
- 100s of warnings, notably:
    - Unused subparts in RN5, RN?
    - Undesignated part
    - Unconnected lines

Maybe change project setings to ignore multiple net names and no driving source for input pins (most of them just are driven through resistors).

**Comment by gkasprow** [comment]
I won't change settings - I found a few issues examining the warnings. 
We have to leave it as it is.

**Comment by gkasprow** [comment]
I added specific No ERC  to supress the warnings
