### ISSUE TITLE
Polygon issues

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Fastino#111]
- [x] Top GND polygon spills over to board edge beyond keepout
![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/93e76fbc-1fce-4305-8b67-c7a4175d3d65)

- [ ] Replace extra GND polygons to no net copper balancing? E.g. on outermost layers

**Comment by gkasprow** [comment]
I don't want to change sth that works on Fastino. It might affect noise performance.
