### ISSUE TITLE
Unmasked vias

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Fastino#112]
- [ ] ![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/0cbc0eed-ca7f-48bf-97bb-562935c532de)
- [ ] ![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/13b3f583-3348-469a-8594-5162aa14bb59)
- [ ] ![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/23cbb55b-ec27-4a5e-90ac-574231d3d678)

**Comment by gkasprow** [comment]
fixed
