### ISSUE TITLE
Routing problems

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Fastino#120]
- [ ] ![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/52cec34f-e16c-4b56-867f-846817d7ad9c)
- [ ] ![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/7efc1082-edc8-46d7-b4e4-2c6c2f505a1e)
- [ ] ![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/461d0a99-fe2b-4a54-a36c-b090ce6cfdfe)
- [ ] ![obraz](https://github.com/sinara-hw/Fastino/assets/24512604/c79d15e1-f5f5-4bd8-a461-7bde5a0836e2)

**Comment by gkasprow** [comment]
done
