### ISSUE TITLE
DAC - FPGA pinout

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Fastino#20]
### 3.3V SPI banks

* Make sure each DAC covers exactly 2 PIO pairs with its four signals. Which pins of the R/T/B side are part of which PIO pair seems a bit hard to find, the only location I can see right now is the [icebox source](https://github.com/cliffordwolf/icestorm/blob/0ec00d892a91cc68e45479b46161f649caea2933/icebox/icebox.py#L4721-L4928). You can also tell from the missing IOx_yyy numbers in the odd/even pairs. The unpaired pins (the other PIO side is not bonded out) are: E14 M15 T13 M7 B4 J12 R4 J11 D14 B8 K15 D8 R16 A7 T15 R6 C13 A9. Use those for I2C, switches, hwrev, LEDS.
* Make sure that the CS and LDAC signals share a PIO pair and that SDx and CLK share the other.
* Make sure the DACs split up evenly across the banks. I.e. 12 per bank max, otherwise the limited clock enable routing might be annoying later. And it distributes the simultaneous switching noise and ground bounce a bit.
* Try to keep each group of 4 DAC channels within one bank and not split them.

### Misc

* No need for the CFG_RELOAD pin and resistor. The SB_WARMBOOT primitive can do that internally.
* Add 2 hw_rev bits and signals to the FPGA.

**Comment by gkasprow** [comment]
I added all the required test points. The one on FPGA are in 2V5 bank
