### ISSUE TITLE
SPI routing/termination/leakage

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Fastino#22]
* Please route the SPI CLK lines away from the data/cs/ldac lines if possible.
* We are planning to spend a significant time updating all 32 DACs at full rate (50 MHz SPI, 32 channels, 2.55 MS/s each channel). Do you think this will be problematic in terms of digital feedthrough, ground bounce, simultaneous switching, filter crosstalk? Do we need series termination on SCLK/SDI if that would help with feedthrough?

**Comment by gkasprow** [comment]
For such speed, it's worth adding at least series termination on the DAC clock lines. The only unknown is resistance if ICE40 in CMOS mode.
Another worry is ground bouncing. This chip has just a few power pins. The datasheet just says obvious things about SSO, without strict recommendations.

**Comment by jordens** [comment]
I am running the prototype on banker currently with lots of SSO activity. How would I measure 
and quantify whether there is too much ground bounce? Just power supplies across a cap? Or would I see it on a supposedly steady output (high or low)?

**Comment by gkasprow** [comment]
Use two outputs, one H, one L and connect the probe between GND and the outputs

**Comment by jordens** [comment]
I'll check.

Re series termination, there are IBIS models for the lattice FPGAs IIRC that should give you some idea of the output impedance.

**Comment by jordens** [comment]
The output impedance of a CMOS driver on ice40 is 20 Ohm. That's what they use in the pseudo-LVDS source matching network.

**Comment by jordens** [comment]
On Banker, there is about 50-100 mV pk-pk of oscillation on a low output and 200-300 mV pk-pk on a high output in the same bank as 32 toggling 50 MHz SSO.

**Comment by gkasprow** [comment]
This is the value I'd expect with such a low number of power supply pins. We can slightly improve it by setting unused pins as outputs and connecting them with supplies so they behave as extra power pins. We don't have many of them though.

**Comment by jordens** [comment]
One other option would be to delay half of the SPI buses in a bank by half a SPI clock cycle. That would partially cancel some bouncing.

**Comment by gkasprow** [comment]
Yes, this would help. Anyway, the margin is still high, especially for 3.3V supply. We are more sensitive for a low logic level because it must be <0.8V. For H we have a lot of margins so 300mV is fine.

**Comment by gkasprow** [comment]
I've selected the longest line connecting DAC28 and FPGA and did some SI analysis.
the Eye diagram with PRBS at 50MHz looks not so bad:
![obraz](https://user-images.githubusercontent.com/4325054/66356284-c60c2280-e96a-11e9-9806-219ae5fb89bd.png)

**Comment by gkasprow** [comment]
with 100R + 100p at  the eye diagram looks much better
![obraz](https://user-images.githubusercontent.com/4325054/66356387-0ff50880-e96b-11e9-852c-163ef777cdc5.png)

**Comment by gkasprow** [comment]
150Ohm + 47p gives nicer results
![obraz](https://user-images.githubusercontent.com/4325054/66356480-56e2fe00-e96b-11e9-8474-8b14721225af.png)

**Comment by gkasprow** [comment]
I added two signals: 50MHz clock at the CLK line, 50MHz PRBS to the DIN and 3MHz 10% duty cycle signals to the LDAC and NSS.
And the crosstalk exceeds 500mV. I'm not surprised by that fact. I planned to place clock lines on the other layer to minimise the coupling.

**Comment by gkasprow** [comment]
After I terminated all inputs with 90R + 100p the signals looks not that bad:
![obraz](https://user-images.githubusercontent.com/4325054/66357177-31a3bf00-e96e-11e9-9549-0e3818c6f321.png)

**Comment by gkasprow** [comment]
The simulations include DAC and FPGA IBIS models

**Comment by hartytp** [comment]
Good wprk!

**Comment by jordens** [comment]
Very nice

**Comment by jordens** [comment]
LDAC and NSS ase also edge sensitive. Let's assume for now we ignore LDAC and keep that asserted.
The crosstalk from DIN to NSS may also be an issue. I don't know how bad it is but we can't have unexpected edges on NSS.

**Comment by gkasprow** [comment]
Anyway, I will move critical lines to the other layer and add RC termination on every DAC.
There is no reason to save a few $ on 6 layer PCB, the cost will be dominated by the components anyway.

**Comment by hartytp** [comment]
> There is no reason to save a few $ on 6 layer PCB, the cost will be dominated by the components anyway.

Agreed. Use as many layers as you need to get a good design.

**Comment by jordens** [comment]
Since we are now loading the lines, doesn't this make sso bounce worse?

**Comment by gkasprow** [comment]
It will to some extent. I can also add series termination but I'm not sure if it would fit.

**Comment by gkasprow** [comment]
no way to fit series termination. We have to live with a RC one. 
We can mount it selectively, only for the longest traces or only if SI issues emerge.

**Comment by jordens** [comment]
If this proves to dense, we could consider running SCK and maybe even CS_N/LDAC in banks of 4 or 8.
