### ISSUE TITLE
BSH103 has 8 V_GS max

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Fastino#23]
I can't tell whether the 100k make it completely safe.

**Comment by gkasprow** [comment]
good catch!
I will replace them with BSS138

**Comment by jordens** [comment]
I think you have used those FETs in other projects as well but I can't remember whether they are on 12V anywhere. Maybe worth going around and checking.

**Comment by gkasprow** [comment]
good idea. I used them mainly for sensing low voltages and driving LEDs due to low Vgth

**Comment by gkasprow** [comment]
I did F search across all the designs and they are used in:
Phaser, Fastino, Kasli

**Comment by gkasprow** [comment]
replaced them in 12V applications.
