### ISSUE TITLE
3V3_MP

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#27]
- [ ] is it actually worth the effort using 3V3_MP for some things, or should we just scrap it and use the 3V3 rail for everything (should simplify the layout merging the planes)

**Comment by gkasprow** [comment]
The idea behind it is to enable the discovery of the boards before 12V is applied. We don't use it at the moment but in case we switch to more advanced power management in the future (CPCIS backplane) it would be helpful. For the moment it does not cost us a single penny.

**Comment by hartytp** [comment]
Ok
