### ISSUE TITLE
cosmetics

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#28]
- [x] Cosmetic: why do R170 and R171 have the value "undefined" rather than just being DNPd in this variant with a red cross? Doesn't that screw the bom/make populating them later on harder (since the value they should have in a populated variant is not shown)

**Comment by hartytp** [comment]
- Cosmetic: why is the power budget an excel file instead of the pretty looking annotations we normally have? Doesn't really matter, I suppose, but nice to keep all the designs consistent and pretty!

**Comment by gkasprow** [comment]
With complex circuits, it's easier to do calculations with Excel, especially when something changes in the meantime.
