### ISSUE TITLE
different ouput op amp

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#3]
https://www.analog.com/media/en/technical-documentation/data-sheets/ADA4625-1-4625-2.pdf may also work and is half the price of the OpAmp on stabilizer. Slightly lower BW so need to re-do filter simulation.

@gkasprow do you have a spice model of the AFE of Stabilizer including all relevant noise sources?

**Comment by gkasprow** [comment]
All simulations are [here](https://www.dropbox.com/sh/iv3qgrgfrsztj9w/AAB7AWFddpc1Nh-4yLUgz0Xma?dl=0) Filters were simulated with ADISimPE. The tool has noise analysis but I'm not sure if components have right noise models because the opamp model file is encrypted.

**Comment by hartytp** [comment]
Thanks! I'll have a play with that.

**Comment by dnadlinger** [comment]
See #4 and discussion in #2; OPA197 looks like a good candidate.

**Comment by hartytp** [comment]
@gkasprow we've selected the OPA197 as our amplifier. Please close once that's on the schematic

**Comment by gkasprow** [comment]
I used dual version, OPA2197. The schematic is already in releases - I replaced the old one.
