### ISSUE TITLE
SMPS passives

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#32]
@gkasprow not that it really matters, but why are we not using the data sheet recommended values for the passives on IC18? 

![image](https://user-images.githubusercontent.com/21218399/67473743-2aa5cd80-f64b-11e9-9f77-c9947636760e.png)

**Comment by hartytp** [comment]
Same for IC90

**Comment by gkasprow** [comment]
for 1.2V is fine. But other voltages require E94 resistors that are not common. I prefer to recalculate them to E24 values and keep the RC the same.
