### ISSUE TITLE
scrap P5V0?

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#36]
- [x] Do we need to increase P5V0A to 5V1 or something to ensure that the DAC Vdd is always higher than Vref (even when taking component tolerances into account)? Before doing this, please confirm that there is nothing else on that rail that can't handle the change in voltage.

**Comment by hartytp** [comment]
hmm...or can we just scrap P5V0A and use only P5V5A instead?

**Comment by gkasprow** [comment]
At the moment, the 5V0 rail is actually 5V1.

**Comment by hartytp** [comment]
Ian there any harm having a single 5V5 rail (or even 5V4)? Simplifies things

**Comment by gkasprow** [comment]
I'd use single P5V4 for all circuits. This is to make sure we never exceed 5V5 for DACs
