### ISSUE TITLE
design review

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#39]
- [x] power budget needs updating to reflect the fact that we now have a single 5v4 rail, not 5V0 and 5V5
- [x] why have you annotated the `_LX` nets? what do you connect to them?
- [x] since you're now using the PG output of IC13, I assume you meant to add a PGFB divider there as well?
- [x] Don't the ref buffers need 10uF ceramic input caps to ensure stability? Currently they are electrolytic, which could be too high ESR/ESL 
- [x] ref buffer Ilim still does not match the annotation (data sheet says it's 125mA/kOhm, but it's a 220Ohm resistor, which does not match the 27.5mA specified current limit)

Other than that, all looks good to me! Assuming @jordens has no final feedback, let's send.

@jordens NB the new requirement to enable the AFE power supply from the FPGA.

**Comment by hartytp** [comment]
@gkasprow one other thing: the 4 special LEDs on the FP have two-letter names, which can be a bit unclear to new users. Could we have something like an annotation of the first page that explains the functions of these LEDs?

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/67643269-e732b400-f915-11e9-9873-44c5f233a172.png)
PG - power good
FD - FPGA done
OT - overtermp
UL - User LED

I placed it also on the schematic

**Comment by gkasprow** [comment]
_LX nets are for Hyperlynx to know where the power lines are. I can remove after simulations.

**Comment by hartytp** [comment]
If you haven’t finalised the files can we swap ul for err or something. It will be a crc error on the data link

**Comment by hartytp** [comment]
Anyway thanks again for another really lovely design! Very much looking forward to testing it on ions

**Comment by gkasprow** [comment]
OK, ERR is fine.
