### ISSUE TITLE
Channel SMPS/switching/SPI/update spur differences

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Fastino#50]
* Kasli, EEM0 -> Fastino channels 24-31 -> IDC-BNC
* battery powered
* modules close together (that does not make any difference)
* in a shielded crate (admittedly not fully RF-tight but that doesn't make a difference)
* voltages in the 6-9 V range (channel << 11 loaded into the DACs)
* all DACs continuously updating at 2.55 MS/s with 21 ns SPI period
* 6.9 kHz bandwidth, 1 M impedance, look at the green trace

The DAC channels are pretty different in terms of their spur performance. 27 is really nice and clean, 31/26/24 are pretty dirty. They have spurs at 450-600 kHz and in the MHz range.

Probably layout tightness, layer crossings, and general routing.

## channel 27:

![image](https://user-images.githubusercontent.com/1338946/72254252-c0764680-3603-11ea-8255-3238100b8536.png)

## channel 24:

![image](https://user-images.githubusercontent.com/1338946/72254220-b5231b00-3603-11ea-9ffb-0968964a7ca6.png)

## channel 26:

![image](https://user-images.githubusercontent.com/1338946/72254239-bb18fc00-3603-11ea-832d-9925a715c2bd.png)

## channel 31:

![image](https://user-images.githubusercontent.com/1338946/72254269-c9671800-3603-11ea-8b0f-6012b019e534.png)

**Comment by hartytp** [comment]
Many thanks for posting that data @jordens 

To check I understand the units, is the worst-case spur you've observed something like `-85dBVrms=56uVrms`.

For a first hw revision, I find that pretty encouraging. The worst-case in-band voltage spurs are only something like 1 OOM above the noise floor and the high-frequency stuff should be okay to remove with a trap filter. Out of curiosity, what's the noise BW from these measurements/what in-band noise floor do you measure?

Still, worth looking again at the layout with this data and seeing what we can do to improve for the next revision...

**Comment by hartytp** [comment]
Crudely, by eye, the filter response looks about right, which is good!

**Comment by jordens** [comment]
See #51 for that.

**Comment by dnadlinger** [comment]
Is this with the swapped output filter resistors manually reworked, or with an unmodified board (i.e. with the extra output offset)?

**Comment by gkasprow** [comment]
@jordens did you try that on another Fastino board?

**Comment by gkasprow** [comment]
Output traces of affected channels
![obraz](https://user-images.githubusercontent.com/4325054/72292061-f4c42400-3650-11ea-91f0-02fa644b8445.png)

**Comment by gkasprow** [comment]
I don't see why these channels are noisy. Did you generate 3.125 sinewave on all outputs?
Can you measure the noise without updating the channels?

**Comment by hartytp** [comment]
@gkasprow can you remind me which channel is which on that diagram? Also, can you remind me where the refs for each channel are routed?

**Comment by hartytp** [comment]
> 27 is really nice and clean, 31/26/24 

27 is right by the connect edge of the board, while 31/26 are close to the SMPS/FPGA so it somewhat makes sense they would be nosier.

24 is right next to 27 and derive from the same ref buffer so that difference isn't obvious.

**Comment by gkasprow** [comment]
other channels like 23, 29 is as close as 31 and 26 to the SMPS. Channel 8 is the closes to the FPGA
Channels 29, 23, 26 are the closest to the SMPS.
SMPS is sitting on the copper island to avoid current loop below.

**Comment by gkasprow** [comment]
It needs careful investigation. I'd disable the SMPS first or at least correlate its frequency with the spur.

**Comment by hartytp** [comment]
Easier said than done. In most of our lab space I’d struggle to reproduce @jordens data since the ambient emi is a nightmare.

**Comment by gkasprow** [comment]
The same in my lab. I have a few FM and DVBT transmitters nearby. It's impossible to measure 100mV 100MHz signal with a scope...

**Comment by hartytp** [comment]
Supposedly our shiny new building will have low EMI. I've budgeted some time to test Fastino once the software is ready. If I can reproduce this then I'll have a look at it (I suspect the easiest thing is to measure the frequencies of the various noise sources and see how they compare to the measured spur frequencies).

**Comment by gkasprow** [comment]
This is exactly what I do. Make a small air coil and sniff with scope in search of EMI sources.

**Comment by jordens** [comment]
This is the only v1.0 I have with all output networks patched. The patch works. Voltages are ok.

I didn't generate a 3.125 sine wave (MHz? V?).

This is a 25 year old office building, with a massive mains/network/phone cable duct running 2 m away from the setup, a bunch of office and lab/RF equipment in the same room, a tram line outside in 50 m distance, the corresponding tram substation in 20 m distance, kitchen with microwave at 20 m, a forest of cell towers at 100 m (20m up), and other labs and companies doing high power audio and wireless development in the adjacent floors and buildings. Certainly not clean. It's a really nice exercise to figure out what matters and what doesn't matter.

The really weird difference is between 24 and 27.

**Comment by hartytp** [comment]
> The really weird difference is between 24 and 27.

Indeed.

From a quick skim over the schematic, the most likely offender for the 450kHz stuff looks to be the 3V3 SMPS. It's also not filtered (beyond the main switching LC) and goes all over the board due to e.g. LEDS, signals like REF shutdown, etc. I haven't looked at the layout in enough detail to offer an explanation for the difference in noise between ch 24/27 though.

@jordens if you have time at some point, it would be really interesting to grab a trace of the P3V3 rail and compare the spectral content on that to the noisy DAC outputs.

**Comment by jordens** [comment]
@gkasprow ah you mean the lowest FFT bin at 3.125 kHz? That's just window leakage from the DC 0 Hz bin.

**Comment by pathfinder49** [comment]
I've just attempted to replicate this measurement on a 4GHz scope using a 500 MHz probe. I believe the noise peaks above are aliased.

Sampling at 20 MS/s (I believe this is how the above data was taken) I get this spectrum:
![CH0 4 5V AC COUPLED WIDE fft](https://user-images.githubusercontent.com/14295481/73215956-ff9caf80-414c-11ea-88ea-82f7ee7746ae.png)

Sampling at 2 GS/s the 500 kHz features disappear and significant 100 MHz noise becomes apparent:
![CH0 4 5V AC COUPLED v2 WIDE fft](https://user-images.githubusercontent.com/14295481/73216444-e8aa8d00-414d-11ea-8382-1cdbf7f41a45.png)

Sidenote: all channels I've looked at show a ~1 us beat between 100 MHz signals. The time basis trace looks like this:
![CH0 4 5V AC COUPLED](https://user-images.githubusercontent.com/14295481/73216788-8e5dfc00-414e-11ea-97c7-f657995477f2.png)
Focusing on a noise spike we see this:
![CH0 4 5V AC COUPLED zoom](https://user-images.githubusercontent.com/14295481/73216794-9158ec80-414e-11ea-9b41-467ab191adde.png)

**Comment by hartytp** [comment]
Glad you got that up and running. Let's have a look tomorrow, but I suspect that with a scope probe that's largely pickup from the lab.

**Comment by gkasprow** [comment]
How did you connect the GND clip?
Please repeat the same measurement, with the same GND connection. Just touch the GND connection with the probe tip and post the results. In this way, you will measure what induces on the probe cable shield.

**Comment by pathfinder49** [comment]
The GND clip is connected via a 20 cm ribbon cable. connecting to a header with soldered wires.

Here are 2 (savgol-filtered) measurements I made today. The y axis should be comparable. 
| clipped on DAC P | Touching GND clip (not moved) |
|-----|-----|
| ![CH0 4 5V AC COUPLED v3 WIDE fft](https://user-images.githubusercontent.com/14295481/73262196-88efc880-41c5-11ea-8a0e-bacd0cd7f11d.png) |  ![CH0 4 5V AC COUPLED gnd WIDE fft](https://user-images.githubusercontent.com/14295481/73262211-91480380-41c5-11ea-9de4-831e4764c606.png) |

**Comment by gkasprow** [comment]
SO, you are essentially measuring the ground loop noise. Try to substract the two :)

**Comment by pathfinder49** [comment]
> * all DACs continuously updating at 2.55 MS/s with 21 ns SPI period

@jordens How did you configure the DACs to continuously update? From our discussion on Mattermost it sounded like you didn't use DMA. However, I only see the SCLK toggling when 
 my experiment continuously writes values to the DAC.

**Comment by jordens** [comment]
You need to change the gateware to make it update all the time.

**Comment by jordens** [comment]
> For a first hw revision, I find that pretty encouraging.

What's "good" level of spurs?
"One LSB" doesn't make much sense and figuring out a generic and practically meaningful bandwidth to integrate the wideband noise over is pretty much impossible.
But there is one value to compare the -87 dBV to: This is only 13 dB better than what would be allowed on conducted emissions on the power line coming from domestic device (CISPR 22 class B requires less than 46 dBµV).
Maybe something like -120 dBV (46 dB better than CISPR 22 class B and about 70 dB better than a 10 mV ripple on a SMPS power supply rail, depending on harmonic content) would be a worthy goal for a low-noise/low-spur DAC output.

**Comment by hartytp** [comment]
@jordens any objections to closing this? This is quite different on the new layout and AFAICT most of the spurs you pointed to are gone.

**Comment by jordens** [comment]
As long as you keep track of the underlying issue, sure.

**Comment by hartytp** [comment]
> As long as you keep track of the underlying issue, sure.

For the avoidance of confusion, which issue exactly do you mean?

**Comment by jordens** [comment]
Given that there are several issues potentially playing into this, we should document a specification for the spurs and ensure that we track and look at several/all channels and all spurs, each time there is an attempt to fix class of spurs. I don't have the overview of assigning the spurs displayed here to the different underlying issues (SMPS on 12V from Kasli, cross-talk from CS/CLK/MOSI through the chip, cross-talk from the terminations through vias or cuts or radiatively, cross-talk from the SMPS on Fastino, through the references or onto the analog path). But I'm happy if someone says that those issues are being addressed and are reasonably likely to have caused the spurs in v1.0.

**Comment by hartytp** [comment]
ACK. I think all that information does exist in the issues, but not in a form that's easy to follow.

I believe that we understand the vast majority of the spurs now and v1.2 should be very clean (v1.1 already looks good on all but a few channels). It will be interesting to see the data though...
