### ISSUE TITLE
N12V0A oscillating on some boards

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Fastino#54]
I have 2 Fastino boards for testing. One of these has a 20 mVp-p, ~1MHz oscillation in the N12V0A supply. The frequency of this oscillation does not appear to coincide with other frequencies observed on the board. This noise propagates couples with different amplitudes into various output channels.

Here are some supply noise spectra for comparison.
![image](https://user-images.githubusercontent.com/14295481/73656686-9820bb80-4688-11ea-8cc9-d723cba98d64.png)

**Comment by pathfinder49** [comment]
I believe I also saw the N12V0A supply oscillating on the other board in some configurations, but have been unable to replicate this.

**Comment by hartytp** [comment]
Could be the load capacitance for the LDO (see the part data sheet section on stability/capacitance). Try adding an extra 10uF ceramic right by the LDO and see if that stabilizes it.

**Comment by hartytp** [comment]
How do these spurs compare with the noise on the dac  outputs?

**Comment by pathfinder49** [comment]
> How do these spurs compare with the noise on the dac outputs?


Dac outputs are the bottom grouping. Lowest trace is the noise floor.
![image](https://user-images.githubusercontent.com/14295481/73659529-57c43c00-468e-11ea-8f14-78cf77b1f4b1.png)

**Comment by hartytp** [comment]
Ok so the worst spurs are due to the 3V3MP and the N12VOA. Interesting.

**Comment by pathfinder49** [comment]
> Ok so the worst spurs are due to the 3V3MP and the N12VOA. Interesting.

I'm currently investigating one other significant spur that seems to behave differently.

**Comment by hartytp** [comment]
Will be interesting to see if a larger output capacitor fixes this. C30 is a 16V X50 22uF, minimum output capacitor is 10uF so I would have expected that to be stable. It's also possible that something else funny is going on with that rail...

**Comment by pathfinder49** [comment]
Adding 10uF (x5R) in parallel to C30 resolves the oscillation.

**Comment by hartytp** [comment]
Sounds like a marginal capacitance then.

@gkasprow can you check for other places in Sinara we're using this LDO please?

**Comment by gkasprow** [comment]
16V 22uF X5R caapcitor has much less than 10uF. X7R would be better here
![obraz](https://user-images.githubusercontent.com/4325054/73662807-bbedfc80-469c-11ea-8cff-65b50691ec97.png)

**Comment by dnadlinger** [comment]
@hartytp: Seems like we have been shouting helpful suggestions at @pathfinder49 in parallel (and were both right!). Do you/do we have a Sinara review checklist template somewhere we could add this to?

**Comment by hartytp** [comment]
> Do you/do we have a Sinara review checklist template somewhere we could add an item for this to? (It's a common, well-known trap, but still has bitten us more than once already.)

Nope, but we should. The main wiki would probably be the best place. IIRC someone uploaded a CERN hw review checklist there. But, a shorter debugging list with the things we always tend to get wrong would be helpful as well...

**Comment by gkasprow** [comment]
It's well hidden here
https://github.com/sinara-hw/sinara/wiki/SchematicsReviewChecklist
