### ISSUE TITLE
Check layer stackup

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#57]
@gkasprow can you do this please?

> Check that the layer stackup is correct and the layers weren't mixed up.

https://github.com/sinara-hw/Fastino/issues/56#issuecomment-584047456

**Comment by gkasprow** [comment]
I'm not sure we can do it without breaking the board. One thing we can do is Xray. I think TS has such capabilities.

**Comment by gkasprow** [comment]
Recently I tested quite a nice technology called laminography.
It's essentially kind of tomography. One can precisely check all aspects of PCB including layer spacing, via connectivity, etc.

**Comment by gkasprow** [comment]
This is an example of the 3-rd layer of PCB 
![obraz](https://user-images.githubusercontent.com/4325054/82495211-0e87e300-9aeb-11ea-8521-44ac96eeaed0.png)

**Comment by jordens** [comment]
Do you have that machine at TS/WUT/CTI?

**Comment by gkasprow** [comment]
It's in another institute (https://www.itr.org.pl/en/) and offer it as a service.
