### ISSUE TITLE
Reduce ground clearance around vias?

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Fastino#67]
Fastino 1.0 has significant digital to analogue crosstalk caused by trace-via coupling (#62). Reducing the via-ground plance may help shield this crosstalk. This should mostly effect traces where there currently is no ground plane between relevand vias and traces.

**Comment by pathfinder49** [comment]
Currently the ground-via clearance is 20 mil. @gkasprow Is a reduction feasible from the production side?

**Comment by gkasprow** [comment]
what do you mean by ground-via clearance? do you mean anti-via diameter?

**Comment by gkasprow** [comment]
the standard distance is 0.2mm between via and the power plane.

**Comment by gkasprow** [comment]
OK. the ground plane distance is 0.2mm but the polygon plane distance is 20mils. This can be reduced to 0.2mm easily

**Comment by hartytp** [comment]
@pathfinder49 Can you keep a change log of all the changes you make to Fastino in your next commit?

It might be worth you fixing the "easy"/uncontroversial things (PSU grounding, design rules/clearance fixes, etc) before you get stuck into the routing.
