### ISSUE TITLE
Altium Component Libraries

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Fastino#68]
@gkasprow Where do I get the correct component libraries for Fastino?

**Comment by gkasprow** [comment]
You can generate it from Fastino

Pozdrawiam,
G.Kasprowicz

________________________________

**Comment by pathfinder49** [comment]
Thanks, maybe I'm not asking the correct question. I'm looking for a capacitor to fix the oscillating N12V0A line. Are there specific libraries, suppliers, etc. I should be choosing from?

**Comment by gkasprow** [comment]
send me private message please
