### ISSUE TITLE
10uF tantalum capacitor alternative

### ISSUE THREAD

**Issue by pkozakiewicz** [sinara-hw/Fastino#74]
AVX TCJA106M016R0200 capacitor is not orderable at the moment. There is no alternative with 0R200 ESR, so we are forced to assembly TR3A106K016C1700 - 1.7 Ohm. Would it cause any trouble with the operation?

**Comment by gkasprow** [comment]
Their role is mainly to dump possible oscillations of the supply rail. That's why I used tantalum caps because ceramic ones have too low ESR. The rail is already supplied from LDOs so noise is not an issue.
1.7Ohm of ESR should be as good as the original one.

**Comment by gkasprow** [comment]
I added it to the BOM as an alternative part. It's back to stock in Farnell, but not available from other vendors.
