### ISSUE TITLE
Discussion: Remove Series termination or Significant rework?

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Fastino#77]
The digital vias associated with the series termination cause significant (capacitive?) crosstalk to nearby analogue circuitry (see #76). This should be addressed in a new revision. Naively, I can see two approaches:
1.  Remove the series termination in favour of keeping the AC-parallel termination. [The parallel termination is the source of some (but not all) -80 dBmV digital to analogue output spurs](https://github.com/sinara-hw/Fastino/issues/75#issuecomment-681074638). These -80 dBmV spurs are the next most significant digital crosstalk I have found.
2.  Place the series termination resistors such that they are further away from the analogue circuits. This is tricky due to the high density of traces near the FPGA. This will almost certainly require a combination of moving the FPGA relative to the DAC channels and adding more layers for digital signals. We may also need to extend the board.

@gkasprow What are your thoughts to expanding the board? Looking at the sparse component and track density on the EEM connector side of the FPGA, it seems like it's possible to move the FPGA several cm towards the EEM connectors. Are there other constraints on the FPGA position space? How much time would such a rework take?

@hartytp I gather you are in favor of option 2. if it proves feasible?

**Comment by hartytp** [comment]
> @hartytp I gather you are in favor of option 2. if it proves feasible?

Broadly, yes. We now have pretty strong evidence that series termination is preferable (gives better SFDR) if it can be done without adding vias near any analog channels.

So, the question is how much work it would take / what compromises we'd have to make to achieve that. Once we know that we can make a decision about whether it's worth it. I suspect that we will end up scrapping the series termination in the end, but let's see what our options are before making a decision.

@gkasprow what options can you see for getting the vias away from the analog channels?

**Comment by gkasprow** [comment]
I think we can scatter the termination resistors on both PCB sides and move them away from the CH9 (CH8).
I don't think it is only an issue with termination resistors proximity, but the slot in the PCB. The vias are placed in such a way that they cut the GND plane on L2, L3. The vias have some inductance and the return current is passing under the problematic channel. Of course, there is a solid P4, P7 plane, but the via of C3_9 is connected to this polygon segment.
![obraz](https://user-images.githubusercontent.com/4325054/91765051-a1e7ae80-ebd8-11ea-9359-2586c326f028.png)
This hypothesis can be verified by desoldering of C3_9 and moving it to an alternative location
![obraz](https://user-images.githubusercontent.com/4325054/91765289-fd19a100-ebd8-11ea-95d4-c7c2110aa58f.png)
Scattering the vias will help with GND integrity.
Another thing that can be done is the increase of distance between pin 3 of IC5_9 and via DAC_LDACn29. This can be easily done by cutting a piece of IC5_9 pad using a sharp blade.  Pin 3 of IC5_9 is a high impedance input and even small coupling is critical.
Yet another place where crosstalk can be reduced is the GND slot placement
If we change the way the track is routed, the return current from neighboring channel won't pass via the via of this channel
![obraz](https://user-images.githubusercontent.com/4325054/91766136-60580300-ebda-11ea-8452-197f0109158e.png)
This should be fixed in every channel

**Comment by gkasprow** [comment]
Once we do the experiments above, we will know more about the coupling mechanisms and what actions to take during the redesign.

**Comment by gkasprow** [comment]
I played a little and moved most of the resistors and vias away from CH8
![obraz](https://user-images.githubusercontent.com/4325054/91770277-31915b00-ebe1-11ea-874a-a4e2783d38ba.png)
![obraz](https://user-images.githubusercontent.com/4325054/91770342-5259b080-ebe1-11ea-801a-3f76c19bbc62.png)

It can be optimized further. There is plenty of space to place the resistors properly - much closer to FPGA then they are now.

**Comment by pathfinder49** [comment]
Great! The series termination may need to beven further way though. In V1.1 the second row of series termination vias seems to still cause -70 dBmV spurs (a 10 dB improvement over the first row). I have circled the termiantion resistors I mean in the image below.
![image](https://user-images.githubusercontent.com/14295481/91772241-65b64d00-ebdc-11ea-9816-5ee77367f99d.png)
Of cause this might be improved by a better ground pour arrangement. 


There are also some more termination resistors that will need addressing.
| The series termination resistors in this image cause significant crosstalk. In paticular, ch17 (ch18 in altium) gives the worst crosstalk to the ch8 (ch9 in altium) analogue output. | I haven't looked at the crosstalk from these series termination resistors. Me might need to back them off somewhat, though they may prove to be fine.|
| --- | --- |
![image](https://user-images.githubusercontent.com/14295481/91771579-20455000-ebdb-11ea-8957-94730e6baa0b.png) | ![image](https://user-images.githubusercontent.com/14295481/91771884-acf00e00-ebdb-11ea-99be-be5d58a1f0a7.png)

**Comment by gkasprow** [comment]
I have a hypothesis that these are not the termination resistors which cause such effect but not properly terminated net segments. In some cases, the termination resistors are placed on the wrong side of the line.  It may cause voltage overshoot at the resistor terminal since the first segment of the line sees much higher impedance. Sorry I didn't catch it during the review.

**Comment by gkasprow** [comment]
I think I managed to move them all - some cannot be moved because they are already very close to the FPGA pins
![obraz](https://user-images.githubusercontent.com/4325054/91917500-60cac980-ecc0-11ea-9f0e-6201f4c489f6.png)
![obraz](https://user-images.githubusercontent.com/4325054/91917524-74763000-ecc0-11ea-8803-3b7d291eb3d2.png)

**Comment by pathfinder49** [comment]
Fantastic! That looks very promising 😃 Good call moving more of the digital traces to L8. 

Is there also space to move the vias further from the analogue channels? From my measurements I think the ones I've circled below would cause crosstalk. 

With the series termination moved, it seems plausible to get ground pour and via stitching between most of the series termination vias and channel 8 (channel 9 in Altium). It would be great if we can find the space for that!
![image](https://user-images.githubusercontent.com/14295481/91918798-ebf59080-ecbb-11ea-9f00-2600e781521c.png)

**Comment by gkasprow** [comment]
I can try to move the entire FPGA

**Comment by gkasprow** [comment]
no way to move the FPGA. I moved some vias and added guard
![obraz](https://user-images.githubusercontent.com/4325054/91965673-1b82b800-ed11-11ea-9d8e-b35541e17527.png)

**Comment by hartytp** [comment]
nice!

**Comment by gkasprow** [comment]
I implemented all the changes; I also fixed a few issues with FPGA power distribution network.

**Comment by pathfinder49** [comment]
I've had a quick look over the changes and this looks great! Definitly a huge improvement 😄 

I've got a few nit-picks. I'd do them myself, but I'm only availible from the 14th. I'll list them here for reference.
- [ ]  These vias seem like they could be moved further from ch8 (altium ch9). More of a peace of mind change in case the guard does not kill the crosstalk.
![image](https://user-images.githubusercontent.com/14295481/92034521-439c0680-ed65-11ea-9851-2e7446b3a4cf.png)
- [ ] Probably just aestetic, why not include ground pour here?
![image](https://user-images.githubusercontent.com/14295481/92034667-7940ef80-ed65-11ea-9059-478bbcac27d6.png)
- [ ] It seems like a good idea to fixup the ground via arrangement in every channel. 
![image](https://user-images.githubusercontent.com/14295481/92035039-07b57100-ed66-11ea-9e94-a2e351e2b965.png)

**Comment by gkasprow** [comment]
in case of vias, the ones on the left side can be moved. But the ones on the right side cannot.

**Comment by hartytp** [comment]
@gkasprow have you finished your work on this?

@pathfinder49 are you okay to have a final review when you return on the 14th? Let's target getting v1.2 sent for manufacture by Friday 18th. Were there any other tests you were planning?

**Comment by hartytp** [comment]
@vnegnev we're aiming to finalize v1.2 next week. Any feedback/change requests before then gratefully received!

**Comment by vnegnev** [comment]
@hartyp No major feedback from us - we'll only start on more thorough tests in a few weeks. Length-matching the tracks from the RTIO headers to the FPGA would be nice, but probably best left to v1.3 since our prototype PCB already compensates for the current lengths.

**Comment by hartytp** [comment]
Thanks!

If you do any more characterization work, please do let us know how you get on

**Comment by gkasprow** [comment]
It's worth checking if we won't have issues with SSO limit of FPGA. Just run all channels with full frequency and see with the scope how the logic levels look like before the termination resistors.

**Comment by pathfinder49** [comment]
I've had a play with moving the vias and was able to increase the distance to the analogue channels further. 
![image](https://user-images.githubusercontent.com/14295481/93212278-4b42ae80-f75a-11ea-92cf-e714bbd70131.png)
I've included this and the other changes mentioned above in #79.

**Comment by hartytp** [comment]
Thanks! Is this ready for a final review by @gkasprow

**Comment by pathfinder49** [comment]
It is

**Comment by hartytp** [comment]
Thanks again for the work on this @pathfinder49 !

@gkasprow can you perform a final review before we send these off to manufacture?

**Comment by gkasprow** [comment]
Sure, hold my beer :)

**Comment by hartytp** [comment]
:)

**Comment by gkasprow** [comment]
please change the rule priority - the LVDS line should be isolated fom GND, otherwize the impedance will be affected seriously
![obraz](https://user-images.githubusercontent.com/4325054/93259154-af3b9600-f79f-11ea-93ec-9b175371e471.png)

**Comment by gkasprow** [comment]
some cosmetic isues 
![obraz](https://user-images.githubusercontent.com/4325054/93259944-ef4f4880-f7a0-11ea-9f27-b7a7e81c6f95.png)
separate the output signals
![obraz](https://user-images.githubusercontent.com/4325054/93260125-3c331f00-f7a1-11ea-9dbe-04aca7842491.png)
![obraz](https://user-images.githubusercontent.com/4325054/93260164-46edb400-f7a1-11ea-986f-948e0e17b4c7.png)

**Comment by gkasprow** [comment]
improve P1V2 polygon 
![obraz](https://user-images.githubusercontent.com/4325054/93260453-b5cb0d00-f7a1-11ea-98ae-a3c923ce3036.png)

**Comment by gkasprow** [comment]
move away LVDS from I2C
![obraz](https://user-images.githubusercontent.com/4325054/93260796-283bed00-f7a2-11ea-83cd-08d40f36f005.png)

**Comment by gkasprow** [comment]
I don't like this noisy 3V3 running under DACs
![obraz](https://user-images.githubusercontent.com/4325054/93261029-7bae3b00-f7a2-11ea-8edb-1626ea5c42e6.png)

Move it to the L3 or BOT and route alongth board edge. Like this:

![obraz](https://user-images.githubusercontent.com/4325054/93261327-d6e02d80-f7a2-11ea-84ff-de2ce5b1f8e2.png)

**Comment by gkasprow** [comment]
reduce coupling of the output signal and 13V rail
![obraz](https://user-images.githubusercontent.com/4325054/93261452-fd05cd80-f7a2-11ea-9be1-5d703feb6b3f.png)
just add local keepout fence or modify the polygon

**Comment by gkasprow** [comment]
move the DAC track away from noisy polygon 
![obraz](https://user-images.githubusercontent.com/4325054/93261828-8b7a4f00-f7a3-11ea-80d6-f2cba0b263e5.png)

**Comment by gkasprow** [comment]
no justification for GND slot - there are SPI lines below, it must be continous. Just add polygon patch.
![obraz](https://user-images.githubusercontent.com/4325054/93262068-e744d800-f7a3-11ea-97bf-9034f3473651.png)

**Comment by gkasprow** [comment]
the board revision should ve 1.2 I believe
![obraz](https://user-images.githubusercontent.com/4325054/93262405-794ce080-f7a4-11ea-8af2-fbfc95bc9d6c.png)

**Comment by gkasprow** [comment]
Other than that, it looks good.

**Comment by pathfinder49** [comment]
> please change the rule priority - the LVDS line should be isolated fom GND, otherwize the impedance will be affected seriously

Which rule do you mean speficically?

> the board revision should ve 1.2 I believe

I've already changed this in the two labels i can see on the boards. Are we both looking at the version in my PR?

I'm adding the other changes to my PR #79

**Comment by gkasprow** [comment]
@pathfinder49 I mean rules priority. For the moment general clearance has higher priority than diff lines clearance, moreover diff clearance is disabled
![obraz](https://user-images.githubusercontent.com/4325054/93314651-5b19cb80-f80a-11ea-984c-06871ed91d6a.png)

**Comment by gkasprow** [comment]
I fixed these diff lines clearance
