### ISSUE TITLE
Potential new DAC

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Fastino#87]
[AD3542R](https://www.analog.com/en/products/ad3542r.html#product-overview)
2ch, 16-bit
15/10 MSPS
Dual SPI with DDR

I haven't done a careful side-by-side comparison.  But could potentially offer a really nice 4-5x speed bump for Fastino if found suitable.  

Chip still in pre-release...

**Comment by gkasprow** [comment]
Yes, the ADI representative was talking that they are aware of the lack of precise 16bit DACs running at ~10MHz rate.

**Comment by dtcallcock** [comment]
They promised a product so perhaps this is it.

**Comment by jordens** [comment]
It's only 7.5 or 5 MS/s if you want to use both channels.

**Comment by gkasprow** [comment]
Right. The clock can go up to 60MHz in the dual data line, 2 Byte,  DDR mode which gives 240Mbit/s data rate and 15MS/s...

**Comment by dtcallcock** [comment]
Another new 'fast' SPI DAC: [AD3552R](https://www.analog.com/en/products/ad3552r.html#product-overview)

Unlike the AD3542R, this one seems to have been released.

DDR quad SPI allows 33 MUPS in 'fast' mode and 22 MUPS in 'precision' mode.  The clock can go up to 66MHz on the quad data line, 2 Byte, DDR mode which gives 528Mbit/s data rate and 33MS/s.  It's a 2ch chip so obviously halve that if running both channels.

Requires external transimpedence amps.

$40 compared to 2x $10 for pair of AD5542A, so twice the silicon cost but nothing crazy.

Noise seems a bit worse not specced the same way in datasheet so not obvious at a glance how much worse.  Needs checking.

Power consumption is about 200mW so 32ch on a Eurocard should be manageable.

**Comment by dhslichter** [comment]
This is getting fast enough that one might do fast transport as well as sinusoidal modulations (e.g. for squeezing, mode-mode coupling, etc).  Would it make sense to look at trying to harmonize gateware/user API between Ultra-Fastino and Shuttler, to reduce wheel reinvention since probably similar signals and parameterizations would be used?

**Comment by dtcallcock** [comment]
> Ultra-Fastino

Surely it should be called '2Fastino'

**Comment by dhslichter** [comment]
I guess maybe the thing to do would be to have "2Fastino" (2Furiousino?) be a variant on an FMC daughtercard, and run it from the EEM FMC Carrier in the same way as Shuttler.  That would cut down on the channel count but still 16 channels is probably doable.

**Comment by gkasprow** [comment]
FMC Shuttler has 125MS/s DACs already, but they are 14-bit ones. 
So we have two options:
- FMC DAC + external 16-channel AFE + ARTIX carrier board
- Updated Fastino with faster DAC and bigger, low-cost FPGA

**Comment by dhslichter** [comment]
I'm not trying to create more work here, so maybe this isn't a great idea.  And I want to keep Shuttler as is because the higher sample rate is important for some of our applications.  I was just thinking out loud about, if one were to make a Fastino variant with some of these faster SPI DACs, if it wouldn't make sense to have the design share more platform features with Shuttler (and its modular FMC nature), and thus be able to harness the gateware development for Shuttler as well.

Not trying to rock the boat here!

**Comment by gkasprow** [comment]
The intention of my comment was a bit different. To decide which way to go, we must first answer the question how much FPGA resources we would need. With EEM FMC carrier we have 100k LC per 16 channels.
With ECP5 FPGA and updated Fastino we have 85k LUT.  Lattice's LUT is not equal to Xilinx's LC of course.
The second question is what use cases do you see for this board that cannot be achieved with Fastino and Shuttler.

**Comment by dtcallcock** [comment]
> The second question is what use cases do you see for this board that cannot be achieved with Fastino and Shuttler.

My thought was that this would be a straightforward replacement for Fastino, as it seems it would really improve its utility for fast-ish transport.  Probably best if big Fastino users like @hartytp weigh in on that though.

**Comment by gkasprow** [comment]
Adding interesting DAC do the list: [AD3552R](https://www.analog.com/en/products/ad3552r.html?ADICID=EMAL_WW_P628000_MIX-NL-PN_1125&deliveryName=DM25392#product-overview)

**Comment by gkasprow** [comment]
Let's close it.
If there is a real need, WUT will design such a board.
