### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Fastino#9]
Wow! That was quick Greg!

**Comment by hartytp** [comment]
@gkasprow I won't do a careful design review until we've finished the high-level design, so am not checking supplies etc yet

I'm also not looking at all at the digital section, since @jordens is doing that.

So, really all I'm looking at right now is the reference, DACs and filters. Apart from the currently open issues, that looks good to me!

**Comment by gkasprow** [comment]
It looks like before we proceed with layout, @jordens need to make sure that ICE40 will do its job.
Right now, I have 2 versions of schematics - with Artix and ICE40.

**Comment by jordens** [comment]
Ice40 will work. Digital aspects are in #16.

**Comment by hartytp** [comment]
@gkasprow what's the timeline for getting a complete schematic RC ready?

**Comment by gkasprow** [comment]
2 weeks

**Comment by hartytp** [comment]
Cool, thanks

**Comment by hartytp** [comment]
@gkasprow what's the state of this? We really need to get these boards to manufacture in the next week or so if possible.

**Comment by gkasprow** [comment]
I'm fighting with the layout. I will finish it till the end of the wee,

**Comment by jordens** [comment]
If this is too dense, let us know. We can relax the design.

**Comment by gkasprow** [comment]
The layout is done. I will publish it for review in a moment

**Comment by hartytp** [comment]
Cool! Let me know when you have a new rc PDF release

**Comment by gkasprow** [comment]
still needs to do SI/PI simulations
PDF is here https://github.com/sinara-hw/Fastino/releases/tag/v1.0rc2

**Comment by hartytp** [comment]
Thanks!

**Comment by jordens** [comment]
Apart from CFG_RELOAD, I2C and HWREV, what changed on the FPGA pinout since the last pinout you posted?

**Comment by gkasprow** [comment]
I think I shifted some of the DAC lines in the IOB to make pins for CLK

**Comment by jordens** [comment]
There is a RED LED for that already.
