### ISSUE TITLE
invalid stack-up

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Fastino#93]
Core on core doesn't work. Should be prepreg dielectric.

![image](https://github.com/sinara-hw/Fastino/assets/1338946/bc90a973-9e16-4b3f-bac0-2cea1efb06d6)

**Comment by gkasprow** [comment]
fixed. In practice, it doesn't really matter because manufacturers change prepreg/core arrangement anyway
![image](https://github.com/sinara-hw/Fastino/assets/4325054/d185a52f-274e-447f-900c-fb30966b6063)
